const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('launcher', {
    minimize:           ()               => ipcRenderer.send('window-minimize'),
    close:              ()               => ipcRenderer.send('window-close'),
    login:              ()               => ipcRenderer.invoke('auth-login'),
    checkAuth:          ()               => ipcRenderer.invoke('auth-check'),
    logout:             ()               => ipcRenderer.invoke('auth-logout'),
    getAllProfiles:      ()               => ipcRenderer.invoke('auth-get-all'),
    switchProfile:      (index)          => ipcRenderer.invoke('auth-switch', index),
    removeProfile:      (index)          => ipcRenderer.invoke('auth-remove', index),
    launch:             (index)          => ipcRenderer.invoke('launch', index),
    getSettings:        ()               => ipcRenderer.invoke('settings-get'),
    setSetting:         (key, value)     => ipcRenderer.invoke('settings-set', key, value),
    fetchNews:          ()               => ipcRenderer.invoke('fetch-news'),
    getCrashLog:        (profileIndex)   => ipcRenderer.invoke('get-crash-log', profileIndex),
    getInstanceNames:   ()               => ipcRenderer.invoke('get-instance-names'),
    setInstanceName:    (index, name)    => ipcRenderer.invoke('set-instance-name', index, name),
    pickBackground:     ()               => ipcRenderer.invoke('pick-background'),
    clearBackground:    ()               => ipcRenderer.invoke('clear-background'),
    detectJava:         ()               => ipcRenderer.invoke('detect-java'),
    exportSettings:     ()               => ipcRenderer.invoke('export-settings'),
    importSettings:     ()               => ipcRenderer.invoke('import-settings'),
    validateTokens:          ()               => ipcRenderer.invoke('auth-validate-tokens'),
    setTitlebarAccount:      (username)       => ipcRenderer.send('set-titlebar-account', username),
    getScreenshots:          (profileIndex)   => ipcRenderer.invoke('get-screenshots', profileIndex),
    openScreenshotsFolder:   (profileIndex)   => ipcRenderer.invoke('open-screenshots-folder', profileIndex),
    onStatus:           (cb)             => ipcRenderer.on('launch-status', (_, msg) => cb(msg)),
    onUpdateAvailable:  (cb)             => ipcRenderer.on('update-available', cb),
    onCompactChanged:   (cb)             => ipcRenderer.on('compact-mode-changed', (_, v) => cb(v)),
});
