name: Build & Release

on:
  push:
    tags:
      - 'v*'          # triggers on tags like v1.0.1, v1.2.0, etc.

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ github.ref_name }} --title "${{ github.ref_name }}" --notes "Trident Client ${{ github.ref_name }}" --repo ${{ github.repository }}

      - name: Build & publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build -- --publish always
